Support Freebsd
google/cpu_features pull request #159
Opened 2021-06-09 05:38 UTC by mldulaney

This patch introduces support for x86 on FreeBSD.  I note that I added the check for FreeBSD on aarch64 to fail in case this gets built on an aarch64 FreeBSD system.

2021-06-09 07:27 UTC, Mizux approved these changes

2021-06-11 19:45 UTC, vishwin commented
Those sysctl names are probably wrong. On a Broadwell system, only `hw.instruction_sse` is present, yet the hardware actually supports much more. `cpuinfo` from `linprocfs` is correct, however, but FreeBSD binaries should not be reading from any Linuxulator interfaces.

2021-06-11 22:06 UTC, mldulaney commented
Hi, any chance this could get merged?

2021-06-12 20:39 UTC, gchatelet requested changes

2021-06-12 20:39 UTC, gchatelet commented on src/cpuinfo_x86.c
> +  features->sse = sysctlbyname("hw.instruction_sse", NULL, NULL, NULL, 1);
As far as I understand, this is not how `sysctlbyname` is supposed to be used.
https://www.freebsd.org/cgi/man.cgi?query=sysctlbyname&manpath=FreeBSD+13.0-RELEASE+and+Ports

One need to set proper arguments.
Also returned value is `0` upon success and `-1` upon failures.
I believe we should rename `GetDarwinSysCtlByName` above and use it here.

2021-06-12 20:39 UTC, gchatelet commented on src/cpuinfo_aarch64.c
> +#endif  // CPU_FEATURES_OS
`// CPU_FEATURES_OS_FREEBSD`

2021-06-12 20:39 UTC, gchatelet commented on src/cpuinfo_x86.c
> +#elif defined(CPU_FEATURES_OS_FREEBSD)
This should probably be merged with the Darwin logic above.

2021-06-25 08:36 UTC, gchatelet commented
I'm closing this PR, FreeBSD support will be handled by #163 which will be submitted as soon as we have FreeBSD support in our CI.

Thank you @mldulaney for the patch: it didn't make it to the repo but it got me interested in solving the issue so it's a worthwhile contribution! (also thank you @vishwin for the comment)

2021-06-25 08:36 UTC, closed without merging